language: zh
pipeline:
- name: MitieNLP
  model: data/total_word_feature_extractor_zh.dat
- name: JiebaTokenizer
- name: RegexFeaturizer
- name: MitieFeaturizer
- name: DIETClassifier
- name: FallbackClassifier
policies: null
